language: java
jdk:
- oraclejdk8
services: postgresql
branches:
  only:
  - travis-tests
before_script:
- psql -c 'create database wegas_test;' -U postgres
- psql -c "create user \"user\" with superuser password '1234';" -U postgres
- sudo apt-get update > /dev/null && sudo apt-get install sshpass
install:
- mvn -P release-profile generate-resources
script:
- mvn -P release-profile install